server:
  port: 8080
application:
   security:
    jwt:
      secret-key: ${JWT_ACCESS_SECRET:"0c090024fd0b368683bfb390b54434dec4c2e79d12370df1cea14e6f050bc64f"}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Enables Eureka-based service discovery
          lower-case-service-id: true # Matches service IDs in lowercase
      routes:
        - id: pet-service
          uri: lb://pet-service # Load-balanced URI via Eureka
          predicates:
            - Path=/service/v1/pets/**
         # filters:
         #   - RewritePath=/pets/(?<segment>.*), /service/v1/pets/$\{segment}
        #  filters:
         #   - StripPrefix=1 # Removes "/pets" from the forwarded path
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/service/v1/auth/**
            
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/service/v1/employees/**
