# Default settings shared across services      
spring:
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0 # 100% of requests are traced (default is 0.1)
      
eureka:
   client:
     serviceUrl:
       defaultZone: ${EUREKA_URI:http://localhost:8761/eureka} # Default Eureka location (can be overridden)
     fetch-registry: true
     register-with-eureka: true
   instance:
     prefer-ip-address: true
    
management: # Enable actuator endpoints
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,refresh # Expose common endpoints


