# Default settings shared across services      
management:
  tracing:
    sampling:
      probability: 1.0 # 100% tracing
    enabled: true

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      
eureka:
   client:
     serviceUrl:
       defaultZone: ${EUREKA_URI:http://localhost:8761/eureka} # Default Eureka location (can be overridden)
     fetch-registry: true
     register-with-eureka: true
   instance:
     prefer-ip-address: true
    
management: # Enable actuator endpoints
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,refresh # Expose common endpoints


