server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee-service
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
