server:
  port: 8761 # Default port for Eureka Server

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false  # The registry itself doesn't need to register
    fetch-registry: false         # The registry doesn't fetch other services
