# Default settings shared across services
spring:
  cloud:
    config:
      uri: http://localhost:8888  # Config Server URL for all apps
      
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka} # Default Eureka location (can be overridden)
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    
management: # Enable actuator endpoints
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,refresh # Expose common endpoints
        
# Default JWT secret - Override in specific service configs or use Vault
jwt:
  secret: "DEFAULT_VERY_SECRET_KEY_REPLACE_IN_PROD_OR_VAULT"
  expiration-ms: 3600000 # 1 hour
